-- Q DISPLAY ALL DATA OF EMPLOYEES TABLE SQL>

USE EMP;

select * from employee;

-- Q DISPLAY FIRST_NAME OF EMPLOYEES TABLE SQL>

SELECT FIRST_NAME FROM EMPLOYEE;

-- Q DISPLAY LAST_NAME AND HIRE_DATE OF EMPLOYEES TABLE SQL>

SELECT LAST_NAME,HIRE_DATE FROM EMPLOYEE;

-- Q DISPLAY FIRST_NAME , SALARY AND NEW SALARY (NEW SALARY = SALARY + 1500) SQL>

SELECT FIRST_NAME,SALARY,SALARY+15000 AS NEW_SALARY FROM EMPLOYEE;

-- Q DISPLAY LAST_NAME , SALARY AND ANNUAL SALARY (ANNUAL SALARY = SALARY * 12) SQL>

SELECT LAST_NAME,SALARY,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE;

-- Q DISPLAY FIRST_NAME , SALARY AND DAILY SALARY (DAILY SALARY = SALARY / 30) SQL>

SELECT FIRST_NAME,SALARY,SALARY/30 AS DAILY_SALARY FROM EMPLOYEE;

-- Q DISPLAY FIRST_NAME AND LAST_NAME IN SINGLE COLUMN WITH PROPER COLUMN ALIAS/HEADING.SQL>

SELECT FIRST_NAME,LAST_NAME,CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME FROM EMPLOYEE;

-- Q DISPLAY GIVEN RESULT FOR EACH EMPLOYEE : Steven works as AD_PRES.SQL>

SELECT FIRST_NAME,JOB_ID,CONCAT(FIRST_NAME,' ',JOB_ID) FROM EMPLOYEE;

-- 13 DISPLAY GIVEN RESULT FOR EACH EMPLOYEE : King's monthly salary is Rs.24000 SQL>

SELECT LAST_NAME,SALARY,CONCAT(LAST_NAME,' ',SALARY) AS MONTHLY_SALARY FROM EMPLOYEE;

-- Q DISPLAY ALL INFO. OF EMPLOYEES TABLE WITH ANNUAL SALARY SQL>

SELECT LAST_NAME,SALARY,SALARY*12 AS ANNUAL_SALARY FROM EMPLOYEE;

-- Q DISPLAY FIRST_NAME , NEW_ANNUAL_SALARY (NEW_ANNUAL_SALARY = SALARY + 1000 * 12) SQL>

SELECT FIRST_NAME,SALARY,((SALARY+1000)*12) AS NEW_ANNUAL_SALARY FROM EMPLOYEE;